export let cwd = (global.cwd = process.cwd)
export let pid = (global.pid = process.pid)
export let stderr = (global.stderr = process.stderr)
export let stdin = (global.stdin = process.stdin)
export let stdout = (global.stdout = process.stdout)
export let uptime = (global.uptime = process.uptime)
