#!/bin/bash
# ../../ of this script
KIT=$(builtin cd "$(dirname ${BASH_SOURCE[0]})"; pwd)

PATH="$KIT/node/bin:$PATH"
NODE_PATH="$KIT/node_modules"
KIT_NODE="$KIT/node/bin/node"
KIT_NPM="$KIT/node/bin/npm"
KIT_PRELOAD="$KIT/preload"

KIT="$KIT" \
PATH="$PATH" \
KENV="$KENV" \
NODE_PATH="$NODE_PATH" \
KIT_NODE="$KIT_NODE" \
KIT_NPM="$KIT_NPM" \
KIT_PRELOAD="$KIT_PRELOAD" \
node \
--require "$KIT_PRELOAD/api.cjs" \
--require "$KIT_PRELOAD/kit.cjs" \
--require "$KIT_PRELOAD/mac.cjs" \
"$@"