export type kenvEnv = {
  KIT_AUTO_UPDATE?: string | undefined
  KIT_BACKGROUND_COLOR?: string | undefined
  KIT_BACKGROUND_MATERIAL?: string | undefined
  KIT_CACHE_PROMPT?: string | undefined
  KIT_CLIPBOARD?: string | undefined
  KIT_CONVERT_KEY?: string | undefined
  KIT_CWD?: string | undefined
  KIT_DEBUG_PROMPT?: string | undefined
  KIT_DISABLE_AUTO_UPDATE?: string | undefined
  KIT_DISABLE_BLUR?: string | undefined
  KIT_DISABLE_GPU?: string | undefined
  KIT_DISPLAY?: string | undefined
  KIT_EMOJI_SHORTCUT?: string | undefined
  KIT_KEYBOARD?: string | undefined
  KIT_MAIN_SCRIPT?: string | undefined
  KIT_MAIN_SHORTCUT?: string | undefined
  KIT_MIC?: string | undefined
  KIT_MEASURE?: string | undefined
  KIT_MONO_FONT?: string | undefined
  KIT_NO_PREVIEW?: string | undefined
  KIT_OPEN_AT_LOGIN?: string | undefined
  KIT_OPEN_IN?: string | undefined
  KIT_SANS_FONT?: string | undefined
  KIT_SEARCH_DEBOUNCE?: string | undefined
  KIT_SERIF_FONT?: string | undefined
  KIT_STDIO?: string | undefined
  KIT_SUSPEND_WATCHERS?: string | undefined
  KIT_TERM_FONT?: string | undefined
  KIT_THEME_DARK?: string | undefined
  KIT_THEME_LIGHT?: string | undefined
  KIT_TRANSPARENT?: string | undefined
  KIT_TRAY?: string | undefined
  KIT_TYPED_LIMIT?: string | undefined
  KIT_WEBCAM?: string | undefined
  KIT_WIDTH?: string | undefined
  KIT_WINDOWS_PRERENDER_TIMEOUT?: string | undefined
  KIT_SEARCH_MIN_SCORE?: string | undefined
  KIT_SEARCH_MAX_ITERATIONS?: string | undefined
  KIT_USE_EXEC_PATH?: string | undefined
}
