export type kenvEnv = {
  KIT_API_KEY?: string | undefined
  KIT_API_PORT?: string | undefined
  KIT_AUTOSTART_SERVER?: string | undefined
  KIT_AUTO_INSTALL?: string | undefined
  KIT_AUTO_UPDATE?: string | undefined
  KIT_BACKGROUND_COLOR?: string | undefined
  KIT_BACKGROUND_MATERIAL?: string | undefined
  KIT_CACHE_PROMPT?: string | undefined
  KIT_CLIPBOARD?: string | undefined
  KIT_CONVERT_KEY?: string | undefined
  KIT_CWD?: string | undefined
  KIT_DEBUG_PROMPT?: string | undefined
  KIT_DOCK?: string | undefined
  KIT_ALWAYS_ON_TOP?: string | undefined
  KIT_AUTO_UPDATE?: string | undefined
  KIT_BACKGROUND_THROTTLE?: string | undefined
  KIT_SHADOW?: string | undefined
  KIT_BLUR?: string | undefined
  KIT_GPU?: string | undefined
  KIT_FRAME?: string | undefined
  KIT_TRANSPARENT?: string | undefined
  KIT_DISPLAY?: string | undefined
  KIT_EMOJI_SHORTCUT?: string | undefined
  KIT_IDLE_PROCESSES?: string | undefined
  KIT_KEYBOARD?: string | undefined
  KIT_MAIN_SCRIPT?: string | undefined
  KIT_MAIN_SHORTCUT?: string | undefined
  KIT_MAIN_SHORTCUT_RETURN_FOCUS?: string | undefined
  KIT_MIC?: string | undefined
  KIT_MEASURE?: string | undefined
  KIT_MONO_FONT?: string | undefined
  KIT_NO_PREVIEW?: string | undefined
  KIT_NODE?: string | undefined
  KIT_OPEN_AT_LOGIN?: string | undefined
  KIT_OPEN_IN?: string | undefined
  KIT_PNPM?: string | undefined
  KIT_PROMPT_INITIAL_HIDE_TIMEOUT?: string | undefined
  KIT_PROMPT_INITIAL_SHOW?: string | undefined
  KIT_PROMPT_INITIAL_X?: string | undefined
  KIT_PROMPT_INITIAL_Y?: string | undefined
  KIT_SANS_FONT?: string | undefined
  KIT_SEARCH_DEBOUNCE?: string | undefined
  KIT_SERIF_FONT?: string | undefined
  KIT_STDIO?: string | undefined
  KIT_SUSPEND_WATCHERS?: string | undefined
  KIT_TELEMETRY?: string | undefined
  KIT_TERM_FONT?: string | undefined
  KIT_THEME_DARK?: string | undefined
  KIT_THEME_LIGHT?: string | undefined
  KIT_TRANSPARENT?: string | undefined
  KIT_TRAY?: string | undefined
  KIT_TYPED_LIMIT?: string | undefined
  KIT_TYPING_RATE?: string | undefined
  KIT_WEBCAM?: string | undefined
  KIT_WIDTH?: string | undefined
  KIT_WINDOWS_PRERENDER_SHOW_INACTIVE_TIMEOUT?: string | undefined
  KIT_WINDOWS_PRERENDER_TIMEOUT?: string | undefined
  KIT_SEARCH_MIN_SCORE?: string | undefined
  KIT_SEARCH_MAX_ITERATIONS?: string | undefined
  KIT_USE_KIT_NODE_PATH?: string | undefined
  KIT_MAIN_ORDER?: string | undefined
  KIT_MAIN_END_ORDER?: string | undefined
  KIT_HIDE_WITHOUT_INPUT?: string | undefined
  GITHUB_SCRIPTKIT_TOKEN?: string | undefined
  KIT_PROMPT_POPUP_WITH_ROUNDED_CORNERS?: string | undefined
  KIT_PROMPT_OFFSCREEN?: string | undefined
  KIT_WINDOWS_OPACITY?: string | undefined
  KIT_LOGIN?: string | undefined
  KIT_BONJOUR_HOST?: string | undefined
  KIT_ALLOWED_ORIGINS?: string | undefined
  KIT_HEALTH_CHECK_INTERVAL?: string | undefined
}
