#!/bin/sh

NODE_PATH={{SIMPLE_PATH}}/node_modules \
DOTENV_CONFIG_PATH={{SIMPLE_PATH}}/.env \
{{SIMPLE_NODE}} \
--require dotenv/config \
--require "{{SIMPLE_PATH}}/preload/core.cjs" \
--require "{{SIMPLE_PATH}}/preload/system.cjs" \
{{SIMPLE_PATH}}/{{type}}/{{name}}.js \
"$@"