#!/bin/bash

KIT=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
args="["
first=true
for var in "${@:2}"
do
  if [ $first = true ]
  then
    first=false
  else
    args+=","
  fi
  args+='"'$var'"'
done
args+="]"

# Check if KIT_MCP_RESPONSE is set
if [ "$KIT_MCP_RESPONSE" = "true" ]; then
  json="{\"script\":\"$1\",\"args\":$args,\"mcpResponse\":true}"
else
  json="{\"script\":\"$1\",\"args\":$args}"
fi
echo $json
curl --http0.9 --unix-socket "$KIT/kit.sock" --header "Content-Type: application/json" \
  --data "$json" \
   "http://localhost"