#!/bin/bash
KIT_CWD="$PWD/node_modules/@johnlindquist/kit" 
KENV_CWD="$PWD" 


KIT="${KIT:=$KIT_CWD}"
KENV="${KENV:="$(cd $KIT/../../..; pwd)"}"

NODE_NO_WARNINGS=1 KIT="$KIT" KENV="$KENV" node \
"$KIT/kit.js" \
"$@"