#!/bin/bash
# ../../ of this script

KIT=$(cd "$(dirname ${BASH_SOURCE[0]})" &> /dev/null && pwd)
KNODE="${KNODE:=$KIT/../.knode/bin/node}"

NODE_NO_WARNINGS=1 \
"$KNODE" \
"$KIT/run/terminal.js" \
"$@"