export enum MODE {
  GENERATE = "GENERATE",
  FILTER = "FILTER",
  MANUAL = "MANUAL",
  HOTKEY = "HOTKEY",
}

export enum CHANNELS {
  GENERATE_CHOICES = "GENERATE_CHOICES",
  TAB_CHANGED = "TAB_CHANGED",
  VALUE_SUBMITTED = "VALUE_SUBMITTED",
  CHOICE_FOCUSED = "CHOICE_FOCUSED",
}
